openai_api_key = "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"  #
app_password = "demo123"  #